//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyExcel.
//     Runtime Version: 4.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasyExcel;

namespace ExcelConfig
{
	[Serializable]
	public class ModifyAttributeBuffData : EERowData
	{
		[EEKeyField]
		[SerializeField]
		private int _ID;
		public int ID { get { return _ID; } }

		[SerializeField]
		private bool _immovable;
		public bool immovable { get { return _immovable; } }

		[SerializeField]
		private bool _disarm;
		public bool disarm { get { return _disarm; } }

		[SerializeField]
		private bool _silence;
		public bool silence { get { return _silence; } }

		[SerializeField]
		private bool _invincible;
		public bool invincible { get { return _invincible; } }

		[SerializeField]
		private bool _invisible;
		public bool invisible { get { return _invisible; } }

		[SerializeField]
		private string[] _valueChanges;
		public string[] valueChanges { get { return _valueChanges; } }


		public ModifyAttributeBuffData()
		{
		}

#if UNITY_EDITOR
		public ModifyAttributeBuffData(List<List<string>> sheet, int row, int column)
		{
			TryParse(sheet[row][column++], out _ID);
			TryParse(sheet[row][column++], out _immovable);
			TryParse(sheet[row][column++], out _disarm);
			TryParse(sheet[row][column++], out _silence);
			TryParse(sheet[row][column++], out _invincible);
			TryParse(sheet[row][column++], out _invisible);
			string[] _valueChangesArray = sheet[row][column++].Split(',');
			int _valueChangesCount = _valueChangesArray.Length;
			_valueChanges = new string[_valueChangesCount];
			for(int i = 0; i < _valueChangesCount; i++)
				TryParse(_valueChangesArray[i], out _valueChanges[i]);
		}
#endif
		public override void OnAfterSerialized()
		{
		}
	}

	public class BuffConfig_ModifyAttributeBuffData_Sheet : EERowDataCollection
	{
		[SerializeField]
		private List<ModifyAttributeBuffData> elements = new List<ModifyAttributeBuffData>();

		public override void AddData(EERowData data)
		{
			elements.Add(data as ModifyAttributeBuffData);
		}

		public override int GetDataCount()
		{
			return elements.Count;
		}

		public override EERowData GetData(int index)
		{
			return elements[index];
		}

		public override void OnAfterSerialized()
		{
			foreach (var element in elements)
				element.OnAfterSerialized();
		}
	}
}
