//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyExcel.
//     Runtime Version: 4.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasyExcel;

namespace ExcelConfig
{
	[Serializable]
	public class ConstructorMechType : EERowData
	{
		[EEKeyField]
		[SerializeField]
		private string _name;
		public string name { get { return _name; } }

		[SerializeField]
		private float _cost;
		public float cost { get { return _cost; } }


		public ConstructorMechType()
		{
		}

#if UNITY_EDITOR
		public ConstructorMechType(List<List<string>> sheet, int row, int column)
		{
			TryParse(sheet[row][column++], out _name);
			TryParse(sheet[row][column++], out _cost);
		}
#endif
		public override void OnAfterSerialized()
		{
		}
	}

	public class ConstructorConfig_ConstructorMechType_Sheet : EERowDataCollection
	{
		[SerializeField]
		private List<ConstructorMechType> elements = new List<ConstructorMechType>();

		public override void AddData(EERowData data)
		{
			elements.Add(data as ConstructorMechType);
		}

		public override int GetDataCount()
		{
			return elements.Count;
		}

		public override EERowData GetData(int index)
		{
			return elements[index];
		}

		public override void OnAfterSerialized()
		{
			foreach (var element in elements)
				element.OnAfterSerialized();
		}
	}
}
