//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyExcel.
//     Runtime Version: 4.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasyExcel;

namespace ExcelConfig
{
	[Serializable]
	public class ConstructorLevel : EERowData
	{
		[EEKeyField]
		[SerializeField]
		private int _id;
		public int id { get { return _id; } }

		[SerializeField]
		private int _cost;
		public int cost { get { return _cost; } }

		[SerializeField]
		private string _color;
		public string color { get { return _color; } }


		public ConstructorLevel()
		{
		}

#if UNITY_EDITOR
		public ConstructorLevel(List<List<string>> sheet, int row, int column)
		{
			TryParse(sheet[row][column++], out _id);
			TryParse(sheet[row][column++], out _cost);
			TryParse(sheet[row][column++], out _color);
		}
#endif
		public override void OnAfterSerialized()
		{
		}
	}

	public class ConstructorConfig_ConstructorLevel_Sheet : EERowDataCollection
	{
		[SerializeField]
		private List<ConstructorLevel> elements = new List<ConstructorLevel>();

		public override void AddData(EERowData data)
		{
			elements.Add(data as ConstructorLevel);
		}

		public override int GetDataCount()
		{
			return elements.Count;
		}

		public override EERowData GetData(int index)
		{
			return elements[index];
		}

		public override void OnAfterSerialized()
		{
			foreach (var element in elements)
				element.OnAfterSerialized();
		}
	}
}
