//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyExcel.
//     Runtime Version: 4.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasyExcel;

namespace ExcelConfig
{
	[Serializable]
	public class SkillData : EERowData
	{
		[EEKeyField]
		[SerializeField]
		private int _ID;
		public int ID { get { return _ID; } }

		[SerializeField]
		private string _name;
		public string name { get { return _name; } }

		[SerializeField]
		private float _cd;
		public float cd { get { return _cd; } }

		[SerializeField]
		private string _description;
		public string description { get { return _description; } }

		[SerializeField]
		private float _manaCost;
		public float manaCost { get { return _manaCost; } }

		[SerializeField]
		private int _distance;
		public int distance { get { return _distance; } }

		[SerializeField]
		private int _range;
		public int range { get { return _range; } }

		[SerializeField]
		private string _skillTargetType;
		public string skillTargetType { get { return _skillTargetType; } }

		[SerializeField]
		private string _skillRangeSelectorType;
		public string skillRangeSelectorType { get { return _skillRangeSelectorType; } }

		[SerializeField]
		private string _skillTargetSelectorType;
		public string skillTargetSelectorType { get { return _skillTargetSelectorType; } }

		[SerializeField]
		private int[] _addBuffs;
		public int[] addBuffs { get { return _addBuffs; } }

		[SerializeField]
		private string _effectPrefab;
		public string effectPrefab { get { return _effectPrefab; } }

		[SerializeField]
		private string _hitFXPrefab;
		public string hitFXPrefab { get { return _hitFXPrefab; } }

		[SerializeField]
		private string _icon;
		public string icon { get { return _icon; } }

		[SerializeField]
		private string _skillBehaviourScriptName;
		public string skillBehaviourScriptName { get { return _skillBehaviourScriptName; } }


		public SkillData()
		{
		}

#if UNITY_EDITOR
		public SkillData(List<List<string>> sheet, int row, int column)
		{
			TryParse(sheet[row][column++], out _ID);
			TryParse(sheet[row][column++], out _name);
			TryParse(sheet[row][column++], out _cd);
			TryParse(sheet[row][column++], out _description);
			TryParse(sheet[row][column++], out _manaCost);
			TryParse(sheet[row][column++], out _distance);
			TryParse(sheet[row][column++], out _range);
			TryParse(sheet[row][column++], out _skillTargetType);
			TryParse(sheet[row][column++], out _skillRangeSelectorType);
			TryParse(sheet[row][column++], out _skillTargetSelectorType);
			string[] _addBuffsArray = sheet[row][column++].Split(',');
			int _addBuffsCount = _addBuffsArray.Length;
			_addBuffs = new int[_addBuffsCount];
			for(int i = 0; i < _addBuffsCount; i++)
				TryParse(_addBuffsArray[i], out _addBuffs[i]);
			TryParse(sheet[row][column++], out _effectPrefab);
			TryParse(sheet[row][column++], out _hitFXPrefab);
			TryParse(sheet[row][column++], out _icon);
			TryParse(sheet[row][column++], out _skillBehaviourScriptName);
		}
#endif
		public override void OnAfterSerialized()
		{
		}
	}

	public class SkillConfig_SkillData_Sheet : EERowDataCollection
	{
		[SerializeField]
		private List<SkillData> elements = new List<SkillData>();

		public override void AddData(EERowData data)
		{
			elements.Add(data as SkillData);
		}

		public override int GetDataCount()
		{
			return elements.Count;
		}

		public override EERowData GetData(int index)
		{
			return elements[index];
		}

		public override void OnAfterSerialized()
		{
			foreach (var element in elements)
				element.OnAfterSerialized();
		}
	}
}
