//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyExcel.
//     Runtime Version: 4.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using EasyExcel;

namespace ExcelConfig
{
	[Serializable]
	public class 技能 : EERowData
	{
		[SerializeField]
		private string _name;
		public string name { get { return _name; } }

		[SerializeField]
		private float _duration;
		public float duration { get { return _duration; } }

		[SerializeField]
		private float _effectiveTimes;
		public float effectiveTimes { get { return _effectiveTimes; } }

		[SerializeField]
		private float _castDelay;
		public float castDelay { get { return _castDelay; } }

		[SerializeField]
		private float _chargingDelay;
		public float chargingDelay { get { return _chargingDelay; } }

		[SerializeField]
		private int _manaCost;
		public int manaCost { get { return _manaCost; } }

		[SerializeField]
		private int _usableCount;
		public int usableCount { get { return _usableCount; } }

		[SerializeField]
		private string _description;
		public string description { get { return _description; } }

		[SerializeField]
		private int _distance;
		public int distance { get { return _distance; } }

		[SerializeField]
		private int _range;
		public int range { get { return _range; } }

		[SerializeField]
		private string _skillTargetType;
		public string skillTargetType { get { return _skillTargetType; } }

		[SerializeField]
		private string _skillTargetSelectorType;
		public string skillTargetSelectorType { get { return _skillTargetSelectorType; } }

		[SerializeField]
		private string _skillRangeSelectorType;
		public string skillRangeSelectorType { get { return _skillRangeSelectorType; } }


		public 技能()
		{
		}

#if UNITY_EDITOR
		public 技能(List<List<string>> sheet, int row, int column)
		{
			TryParse(sheet[row][column++], out _name);
			TryParse(sheet[row][column++], out _duration);
			TryParse(sheet[row][column++], out _effectiveTimes);
			TryParse(sheet[row][column++], out _castDelay);
			TryParse(sheet[row][column++], out _chargingDelay);
			TryParse(sheet[row][column++], out _manaCost);
			TryParse(sheet[row][column++], out _usableCount);
			TryParse(sheet[row][column++], out _description);
			TryParse(sheet[row][column++], out _distance);
			TryParse(sheet[row][column++], out _range);
			TryParse(sheet[row][column++], out _skillTargetType);
			TryParse(sheet[row][column++], out _skillTargetSelectorType);
			TryParse(sheet[row][column++], out _skillRangeSelectorType);
		}
#endif
		public override void OnAfterSerialized()
		{
		}
	}

	public class SkillConfig_技能_Sheet : EERowDataCollection
	{
		[SerializeField]
		private List<技能> elements = new List<技能>();

		public override void AddData(EERowData data)
		{
			elements.Add(data as 技能);
		}

		public override int GetDataCount()
		{
			return elements.Count;
		}

		public override EERowData GetData(int index)
		{
			return elements[index];
		}

		public override void OnAfterSerialized()
		{
			foreach (var element in elements)
				element.OnAfterSerialized();
		}
	}
}
